name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  docker-build:
    name: Build & Push Image
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Build & Push
        uses: juninmd/base-actions/docker-build-push@main
        with:
          image-name: ${{ github.repository }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    name: Deploy to ArgoCD
    needs: docker-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: ArgoCD Deploy
        uses: juninmd/base-actions/deploy-to-argocd@main
        with:
          app-name: meu-livro3
          image-tag: latest
          charts-token: ${{ secrets.GITHUB_TOKEN }}
